services:
  frontend-build:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: build
    container_name: beacon-frontend-build
    env_file:
      - ../frontend/.env.preview
    environment:
      - NODE_ENV=preview
    networks:
      - beacon-network
    volumes:
      - ../frontend:/app
      - ../frontend/dist:/app/dist
      - /app/node_modules
    
  frontend-preview:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: preview
    container_name: beacon-frontend-preview
    ports:
      - "4173:4173"
    env_file:
      - ../frontend/.env.preview
    environment:
      - NODE_ENV=preview
    networks:
      - beacon-network
    depends_on:
      - frontend-build
        
  backend-preview:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: final
    container_name: beacon-backend-preview
    ports:
      - "5003:8080"
    volumes:
      - ../backend:/src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Preview
    networks:
      - beacon-network
    env_file:
      - ../backend/.env.preview      
    
  typegen:
    build:
      context: ..
      dockerfile: ./backend/DockerfileTypeGen
    container_name: beacon-typegen
    restart: "no"
    volumes:
      - ../frontend/src/shared/models/generated:/typegen/generated
      - ../backend:/app/backend
    networks:
      - beacon-network

networks:
  beacon-network:
    driver: bridge