# This is a generated file. Not intended for manual editing.
services:
  backend-preview:
    build:
      context: "/Users/kyleboehlen/RiderProjects/beacon/backend"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/backend.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "backend:dev"
    ports: []
    volumes:
    - "/Users/kyleboehlen/RiderProjects/beacon/backend:/app:rw"
    - "/Users/kyleboehlen/RiderProjects/beacon:/src:rw"
    - "/Users/kyleboehlen/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
